FROM golang:1.23-alpine
WORKDIR /app
RUN apk add --no-cache git ca-certificates wget
RUN go install github.com/air-verse/air@v1.61.7
COPY go.mod go.sum ./
RUN go mod download
COPY . .
EXPOSE 8080
CMD ["air", "-c", ".air.toml"]
